### ISSUE TITLE
RTC.io plugin not getting opened.

### ISSUE THREAD

**Issue by santhoshreddyk** [rtc-io/rtc-screenshare#9]
Hi DamonOehlman,

I have updated new version of rtc.o extension, downloaded new version of screen share and running it with beefy. i took care of ssl and all. But the popup window to select the screen to be selected is not coming up.  I dont see any errors at server side, but client side.
here are the screenshots. Please help me.

![cmd](https://cloud.githubusercontent.com/assets/8919427/6427171/b43984ee-bf9e-11e4-9691-22c27a519e03.png)

![chrome](https://cloud.githubusercontent.com/assets/8919427/6427172/b9c54ce0-bf9e-11e4-9919-05a447703cde.jpg)

**Comment by silviapfeiffer** [comment]
Could you try going to http://127.0.0.1:9966/ instead of just localhost ?

**Comment by DamonOehlman** [comment]
@silviapfeiffer Going to http://127.0.0.1:9966/ won't work because screensharing requires HTTPS to operate.  In fact, with the inline installation it's even more restrictive as the published version of the plugin will only work if is being run from an `*.rtc.io` host.

@santhoshreddyk How are you doing your HTTPS proxying to your local dev server?  I dropped a gist online on Friday to help one of our team members make a setup similar to what you are doing now so that should help (proxying via nginx):

https://gist.github.com/DamonOehlman/dfe879ce2e282a86bc80

Additionally, I think you will probably need to put a local host entry for something like `local.rtc.io` for localhost.

**Comment by santhoshreddyk** [comment]
@DamonOehlman 

I tried the nginx configuration given by you. And changed my localhost to "localhost.rtc.io"
Still it says bundle.js and demo.css --> 404 error and nothing comes up.
Please suggest.

![untitled](https://cloud.githubusercontent.com/assets/8919427/6429664/03389044-c008-11e4-9061-05d6565144dd.png)

**Comment by DamonOehlman** [comment]
@santhoshreddyk ok, I think I see the problem now that I've taken a look again at the command you are using to run the demo.  Try running the demo with the following command:

```
beefy share-window.js:bundle.js
```
This is of course assuming that you are running beefy from within the examples directory as you did in the first instance.  Assuming npm works the same on windows that it does on my machine you should also be able to run the following from the screenshare directory (one above the examples directory) and have it work also:

```
npm run demo
```

This is made possible by a custom script specified in the [package.json](https://github.com/rtc-io/rtc-screenshare/blob/master/package.json#L9).  Let me know how you go.

**Comment by santhoshreddyk** [comment]
@DamonOehlman : Thank you very much for instant reply. It works :)
